<p>Please add a video to your previous review for <?php echo $this->escape($this->company->name); ?>.</p>

<form enctype="multipart/form-data" method="post" class="form-horizontal" action="<?php echo $this->urlGenerator()->companyReviewAddVideoUrl($this->review->Company, $this->review); ?>">
    <fieldset>
        <?php echo $this->videoForm->csrf_token; ?>

        <?php
            foreach ($this->videoForm->getElements() as $element):
                if ($element->getName() == 'csrf_token')
                    continue;
        ?>
            <div class="control-group <?php if ($element->getMessages()) echo 'error'; ?>">
                <label class="control-label" for="<?php echo $element->getId(); ?>"><?php echo $element->getLabel(); ?></label>
                <div class="controls">
                    <?php echo $element; ?>

                    <?php if ($element->getMessages()): ?>
                        <span class="help-block"><?php echo implode('', $element->getMessages()); ?></span>
                    <?php elseif ($element->getDescription()): ?>
                        <span class="help-block"><?php echo $element->getDescription(); ?></span>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Send</button>
                &nbsp;or&nbsp;
                <a href="<?php echo $this->urlGenerator()->companyUrl($this->company); ?>">Go Back</a>
            </div>
        </div>
    </fieldset>
</form>
