<a href="<?php echo ($this->company->uri);?>">&lt;&lt; Back to Company Profile</a>
<br><br>

<?php if ($this->paginator && count($this->paginator)): ?>
    <ul class="article-list">
        <?php foreach ($this->paginator as $article): ?>
            <li>
                <div>
                    <a href="<?php echo $this->urlGenerator()->companyArticleUrl($this->company, $article); ?>">
                        <?php echo $this->escape($article->title); ?>
                    </a>

                    <div class="info">
                        <span class="label"><?php echo $this->dateFormat()->formatFromString($article->created_at); ?></span>
                    </div>

                    <div>
                        <?php echo Main_Service_UrlLinker::process($this->escape($article->intro)); ?>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

    <?php
        if (count($this->paginator) > 1) {
            echo $this->paginationControl(
                $this->paginator,
                "Sliding",
                "pagination/digg_pagination_company.phtml",
                array(
                    "route" => $this->company->local_business ? "company_articles_page" : "company_national_articles_page",
                    "params" => is_array($this->paginatorParams) ? $this->paginatorParams : array($this->paginatorParams),
                )
            );
        }
    ?>
<?php else: ?>
    No articles to display.
<?php endif; ?>
