<ul>
    <li>
        <a href="<?php echo $this->url('category', array( 'id' => 'uncategorized' )); ?>">
           Uncategorized (<?php echo $this->uncategorized->companies_count; ?>)
        </a>
    </li>
    <?php if(count($this->categories)): ?>
        <?php foreach($this->categories as $category): ?>
            <li><a href="<?php echo $this->url('category', array( 'id' => $category->id )); ?>">
                    <?php echo $category->name; ?> (<?php echo $category->companies_count; ?>)
                </a>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>
