<ul>
    <li>
        <a href="<?php echo $this->url('state_city_category', array('state'  => $this->state, 'city' => $this->city, 'category' => 'uncategorized' )); ?>">
           Uncategorized (<?php echo $this->uncategorized->companies_count; ?>)
        </a>
    </li>
    <?php if(count($this->categories)): ?>
        <?php foreach($this->categories as $category): ?>
            <li><a href="<?php echo $this->url('state_city_category', array( 'state'  => $this->state, 'city' => $this->city, 'category' => $category->uri )); ?>">
                    <?php echo $category->name; ?> (<?php echo $category->companies_count; ?>)
                </a>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>