<?php if (isset($this->result) && $this->result === true): ?>
    <p>
        We've sent you an email with a link to reset your password and instructions on how to change it.<br>
        If you won't receive the message within a few minutes, please check your spam folder.
    </p>
<?php else: ?>
    <?php
        echo $this->partial("form.phtml", array(
            'form'   => $this->restoreForm,
            'action' => $this->url('restore'),
            'button' => 'Restore',
            'extraButton' => array(
                'label' => 'Login',
                'url' => $this->url('login')
            )
        ));
    ?>
<?php endif; ?>