<?php

/**
 * Companies_Model_Base_CompanyPromo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property clob $content
 * @property integer $company_id
 * @property enum $status
 * @property Companies_Model_Company $Company
 * @property Doctrine_Collection $company_promo_emails
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Companies_Model_Base_CompanyPromo extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('company_promo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('content', 'clob', 65535, array(
             'type' => 'clob',
             'notnull' => true,
             'length' => '65535',
             ));
        $this->hasColumn('company_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'idle',
              1 => 'new',
              2 => 'all',
             ),
             'notnull' => true,
             'default' => 'idle',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Companies_Model_Company as Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasMany('Companies_Model_PromoEmail as company_promo_emails', array(
             'local' => 'id',
             'foreign' => 'company_promo_id'));
    }
}