<?php

/**
 * Companies_Model_Base_CompanyCard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $company_id
 * @property string $number
 * @property string $exp_date
 * @property string $type
 * @property string $token
 * @property string $name
 * @property string $address
 * @property string $zip
 * @property string $city
 * @property string $state
 * @property Companies_Model_Company $Company
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Companies_Model_Base_CompanyCard extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('company_cards');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('company_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('number', 'string', 16, array(
             'type' => 'string',
             'notnull' => true,
             'fixed' => 1,
             'length' => '16',
             ));
        $this->hasColumn('exp_date', 'string', 7, array(
             'type' => 'string',
             'notnull' => true,
             'fixed' => 1,
             'length' => '7',
             ));
        $this->hasColumn('type', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '1000',
             ));
        $this->hasColumn('token', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('name', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('address', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('zip', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('city', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('state', 'string', 2, array(
             'type' => 'string',
             'length' => '2',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Companies_Model_Company as Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}