<?php

/**
 * Companies_Model_Base_Discount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $plan_id
 * @property string $code
 * @property decimal $first_month_discount
 * @property decimal $monthly_discount
 * @property enum $status
 * @property Companies_Model_Plan $Plan
 * @property Doctrine_Collection $Companies
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Companies_Model_Base_Discount extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('discounts');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('plan_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('code', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1000',
             ));
        $this->hasColumn('first_month_discount', 'decimal', 11, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('monthly_discount', 'decimal', 11, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'active',
              1 => 'deleted',
             ),
             'notnull' => true,
             'default' => 'active',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Companies_Model_Plan as Plan', array(
             'local' => 'plan_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasMany('Companies_Model_Company as Companies', array(
             'local' => 'id',
             'foreign' => 'discount_id'));
    }
}