<?php

/**
 * Companies_Model_Base_Plan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property decimal $setup_fee
 * @property decimal $monthly_fee
 * @property enum $status
 * @property Doctrine_Collection $Discounts
 * @property Doctrine_Collection $Companies
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Companies_Model_Base_Plan extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('plans');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1000',
             ));
        $this->hasColumn('setup_fee', 'decimal', 11, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('monthly_fee', 'decimal', 11, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'active',
              1 => 'deleted',
             ),
             'notnull' => true,
             'default' => 'active',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Companies_Model_Discount as Discounts', array(
             'local' => 'id',
             'foreign' => 'plan_id'));

        $this->hasMany('Companies_Model_Company as Companies', array(
             'local' => 'id',
             'foreign' => 'plan_id'));
    }
}