<?php

/**
 * Companies_Model_Base_PromoEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mail
 * @property integer $company_promo_id
 * @property Companies_Model_CompanyPromo $CompanyPromo
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Companies_Model_Base_PromoEmail extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('company_promo_emails');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('mail', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('company_promo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));


        $this->index('promo_id_mail_unique', array(
             'fields' => 
             array(
              'company_promo_id' => 
              array(
              'sorting' => 'ASC',
              ),
              'mail' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Companies_Model_CompanyPromo as CompanyPromo', array(
             'local' => 'company_promo_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}