<?php

/**
 * Users_Model_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Users_Model_Role extends Users_Model_Base_Role {
    const DEFAULT_ROLE = "guest";
    const ADMIN_ROLE = "admin";
    const SUBADMIN_ROLE = "subadmin";
    const MEMBER_ROLE = "business";
}