<?php

/**
 * Users_Model_RoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Users_Model_RoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Users_Model_RoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Users_Model_Role');
    }
}