<?php

/**
 * Users_Model_UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Users_Model_UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Users_Model_UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Users_Model_User');
    }
    
    /**
     * Users paqination query
     * @param array $fieldsWhere
     * @param bool $skipAdmins
     * @return Doctrine_Query 
     */
    public function getQueryToFetchAll(array $fieldsWhere = NULL, $skipAdmins = false) {
        $adminRoleId = Users_Model_RoleTable::getInstance()->findOneByName(Users_Model_Role::ADMIN_ROLE)->id;

        $query = $this->createQuery('u')
            ->where('u.status = ?', array(Users_Model_User::STATUS_ACTIVE))
            ->orderBy('u.created_at DESC');
        
        if ($fieldsWhere !== NULL) {
            foreach ($fieldsWhere as $field => $value) {
                
                if (empty($value)) {
                    continue;
                }
                
                if ($field == 'search') {
                    $query->leftJoin("u.Company c");
                    $query->addWhere("(u.name LIKE ? OR u.mail LIKE ? OR c.name LIKE ?)", array(
                        '%' . $value . '%',
                        '%' . $value . '%',
                        '%' . $value . '%'
                    ));
                } else {
                    $query->addWhere("u.{$field} = ?", array($value));                    
                }
            }
        }

        if ($skipAdmins) {
            $query->addWhere("u.role_id != ?", array($adminRoleId));
        }
        
        return $query;
    }
    
    public function findOneByHash($hash)
    {
        $user = $this->createQuery('u')->where('MD5(u.mail) = ?', array( $hash ))->execute();
        return $user->count() ? $user->getFirst() : NULL;
    }
    
    /**
     * All admins
     * @return Doctrine_Collection 
     */
    public function getAdmins() {
        return $this->createQuery("u")
            ->select("u.*")
            ->from("Users_Model_User u")
            ->innerJoin("u.Role r")
            ->where("r.name = ? OR r.name = ? ", array(Users_Model_Role::ADMIN_ROLE, Users_Model_Role::SUBADMIN_ROLE))
            ->addWhere("u.status = ?", Users_Model_User::STATUS_ACTIVE)
            ->execute();
    }
}