<?php

/**
 * Companies_Model_CompanyVideoTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_CompanyVideoTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     * @return object Companies_Model_CompanyVideoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Companies_Model_CompanyVideo');
    }

    /**
     * Get about us videos
     * @param $companyId
     * @param $status
     */
    public function getAboutUs($companyId, $status=NULL) {
        $q = $this->createQuery("v")
            ->where("v.company_id = ? AND v.review_id IS NULL", array($companyId));

        if ($status != NULL) {
            $q->addWhere("v.status = ?", array($status));
        }

        return $q->execute()->get(0);
    }

    /**
     * Get unprocessed videos
     */
    public function getUnprocessed() {
        return $this->createQuery("v")
            ->whereIn("v.status", array(
                Companies_Model_CompanyVideo::STATUS_NOT_PROCESSED,
                Companies_Model_CompanyVideo::STATUS_PROCESSING
            ))
            ->execute();
    }

    /**
     * Get review video
     * @param $companyId
     * @param $reviewId
     */
    public function getReviewVideo($companyId, $reviewId) {
        return $this->createQuery("v")
            ->where("v.company_id = ? AND v.review_id = ? AND v.status = ?", array(
                $companyId,
                $reviewId,
                Companies_Model_CompanyVideo::STATUS_PROCESSED
            ))
            ->execute()
            ->get(0);
    }
}