<?php

/**
 * Companies_Model_CompanyCardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_CompanyCardTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     * @return object Companies_Model_CompanyCardTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Companies_Model_CompanyCard');
    }

    /**
     * Get expiring cards
     * @return Doctrine_Collection
     */
    public function getExpiring() {
        $expiring = array(
            date("m/Y"),
        );

        $nextMonth = new DateTime();
        $nextMonth->add(new DateInterval("P1M"));
        $expiring[] = $nextMonth->format("m/Y");

        return $this->createQuery('c')
            ->select('c.*')
            ->whereIn('c.exp_date', $expiring)
            ->execute();
    }
}