<?php

/**
 * Companies_Model_CompanyArticleCommentTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_CompanyArticleCommentTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     * @return object Companies_Model_CompanyArticleCommentTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Companies_Model_CompanyArticleComment');
    }

    /**
     * Get query for article comments
     * @param int $articleId
     * @param bool $onlyPublished
     * @return Doctrine_Query
     */
    public function getQueryAll($articleId = null, $onlyPublished = false) {
        $query = $this->createQuery("c")->select("c.*");

        if ($articleId) {
            $query->where("c.article_id = ?", (int) $articleId);
        }

        if ($onlyPublished) {
            $query->addWhere("c.published");
        }

        $query->orderBy("c.created_at DESC");

        return $query;
    }
}