<?php

/**
 * Companies_Model_CouponReviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_CouponReviewTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     * @return object Companies_Model_CouponReviewTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Companies_Model_CouponReview');
    }

    /**
     * Check if coupon was sent
     * @param $couponId
     * @param $reviewId
     * @return bool
     */
    public function wasSent($couponId, $reviewId) {
        $couponReview = $this->findOneByCouponIdAndReviewId($couponId, $reviewId);

        if ($couponReview !== false) {
            return !empty($couponReview->is_coupon_sended);
        }

        return false;
    }

    /**
     * Mark coupon as sent
     * @param $couponId
     * @param $reviewId
     */
    public function setSent($couponId, $reviewId) {
        $couponReview = $this->findOneByCouponIdAndReviewId($couponId, $reviewId);

        if ($couponReview === false) {
            $couponReview = new Companies_Model_CouponReview();
            $couponReview->coupon_id = $couponId;
            $couponReview->review_id = $reviewId;
        }

        $couponReview->is_coupon_sended = true;
        $couponReview->save();
    }    
}