<?php

/**
 * Companies_Model_DiscountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_DiscountTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     * @return object Companies_Model_DiscountTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Companies_Model_Discount');
    }

    /**
     * Get discount query for pagination
     * @return Doctrine_Query
     */
    public function getQueryActiveDiscounts() {
        return $this->createQuery('d')
            ->select('d.*')
            ->where('d.status = ?', array(Companies_Model_Discount::STATUS_ACTIVE))
            ->orderBy('d.id DESC');
    }
}