<?php

/**
 * Companies_Model_EmployeeTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_EmployeeTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object Companies_Model_EmployeeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable("Companies_Model_Employee");
    }

    /**
     * Get query for company employees
     * @param null $companyId
     * @return Doctrine_Query
     */
    public function getQueryToFetchAll($companyId = null) {
        $query = $this->createQuery("e")
            ->select("e.*")
            ->addSelect("(SELECT ROUND(AVG(r.rating), 2)
                FROM Companies_Model_Review r
                WHERE r.status = '" . Companies_Model_Review::STATUS_PUBLISHED . "'
                AND r.company_employee_id = e.id) as rating")
            ->addSelect("(SELECT COUNT(rc.id)
                FROM Companies_Model_Review rc
                WHERE rc.status = '" . Companies_Model_Review::STATUS_PUBLISHED . "'
                AND rc.company_employee_id = e.id) as review_count");

        if ($companyId) {
            $query->where("e.company_id = ?", (int) $companyId);
        }

        $query->orderBy("e.sorting_position ASC");

        return $query;
    }

    /**
     * Get public employees
     * @return Doctrine_Collection
     */
    public function getPublicEmployees() {
        return $this->createQuery("e")
            ->select("e.*")
            ->where("public_profile")
            ->orderBy("e.name ASC")
            ->execute();
    }
}