<?php

/**
 * Companies_Model_PlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_PlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     * @return object Companies_Model_PlanTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Companies_Model_Plan');
    }

    /**
     * Get the cheapest plan id
     * @return
     */
    public function getCheapestId() {
        $data = $this->createQuery()
            ->select("p.id")
            ->from("Companies_Model_Plan p")
            ->where("p.status= 'active'")
            ->limit(1)
            ->execute();

        if ($data && $data->count() > 0) {
            return $data->get(0)->id;
        }

        return null;
    }
}