<?php

/**
 * Companies_Model_PromoEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_PromoEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Companies_Model_PromoEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Companies_Model_PromoEmail');
    }
}