<?php

/**
 * Companies_Model_Review
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Companies_Model_Review extends Companies_Model_Base_Review
{
    const STATUS_ERROR = 'error';
    const STATUS_NOT_PROCESSED = 'not_processed';
    const STATUS_UNCONFIRMED = 'unconfirmed';
    const STATUS_PROCESSING = 'processing';
    const STATUS_PUBLISHED = 'published';
    const STATUS_RECONCILIATION = 'reconciliation';

    const API_STATUS_PROCESSED = 'processed';
}