<?php

/**
 * Companies_Model_VideoStream
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Companies_Model_VideoStream extends Companies_Model_Base_VideoStream {
    const STATUS_ERROR = 'error';
    const STATUS_NOT_PROCESSED = 'not_processed';
    const STATUS_PROCESSING = 'processing';
    const STATUS_PROCESSED = 'processed';
}