<?php

/**
 * Companies_Model_VideoStreamTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Companies_Model_VideoStreamTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     * @return object Companies_Model_VideoStreamTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Companies_Model_VideoStream');
    }

    /**
     * Get video streams
     * @param $videoId
     */
    public function getVideoStreams($videoId) {
        return $this->createQuery("v")
            ->where("v.video_id = ? AND v.status = ?", array(
                $videoId,
                Companies_Model_VideoStream::STATUS_PROCESSED
            ))
            ->orderBy("v.type DESC")
            ->execute();
    }
}