<h1 class="page-title"><?php echo $this->escape(isset($this->customTitle) ? $this->customTitle : $this->title); ?></h1>
<hr>

<form enctype="application/x-www-form-urlencoded" method="post" class="form-horizontal" action="<?php echo $this->url('business_account'); ?>">
    <fieldset>
        <?php echo $this->changePassForm->csrf_token; ?>

        <?php
            foreach ($this->changePassForm->getElements() as $element):
                if ($element->getName() == 'csrf_token')
                    continue;
        ?>
            <div class="control-group <?php if ($element->getMessages()) echo 'error'; ?>">
                <label class="control-label" for="<?php echo $element->getId(); ?>"><?php echo $element->getLabel(); ?></label>
                <div class="controls">
                    <?php echo $element; ?>
                    <?php if ($element->getMessages()): ?>
                        <span class="help-block"><?php echo implode('', $element->getMessages()); ?></span>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Change</button>
            </div>
        </div>
    </fieldset>
</form>
