Companies_Model_Category:
  tableName: categories
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(100)
      notnull: true
    uri:
      type: string(100)
      unique: true
      notnull: true
