Companies_Model_CompanyArticleComment:
  tableName: company_article_comments
  actAs: [Timestampable]
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:
      type: integer(4)
      primary: true
      unsigned: true
      notnull: true
      autoincrement: true
    article_id:
      type: integer(4)
      unsigned: true
      notnull: true
    email:
      type: string(1000)
      notnull: true
    name:
      type: string(1000)
      notnull: true
    comment:
      type: clob(2147483647)
      notnull: true
    published:
      type: integer(1)
      unsigned: true
      notnull: true
      default: 0
  relations:
    Article:
      class: Companies_Model_CompanyArticle
      local: article_id
      foreign: id
      foreignAlias: Comments
      onDelete: cascade
      onUpdate: cascade
