Companies_Model_Discount:
  tableName: discounts
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true      
      notnull: true
      autoincrement: true
    plan_id:
      type: integer(4)
      unsigned: true
      notnull: true
    code:
      type: string(1000)
      notnull: true
    first_month_discount:
      type: decimal(11)
      scale: 2
      notnull: true
    monthly_discount:
      type: decimal(11)
      scale: 2
      notnull: true
    status:
      type: enum
      values: ['active', 'deleted']
      notnull: true
      default: active
  relations:
    Plan:
      class: Companies_Model_Plan
      local: plan_id
      foreign: id
      foreignAlias: Discounts
      onDelete: cascade
      onUpdate: cascade