Companies_Model_Image:
  tableName: company_images
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(100)
      notnull: true
    extension:
      type: string(100)
      notnull: true
    company_id:
      type: integer(4)
      notnull: true
  relations:
    Company:
      class: Companies_Model_Company
      local: company_id
      foreign: id
      foreignAlias: Images
      onDelete: cascade
      onUpdate: cascade
