Companies_Model_VideoStream:
  tableName: video_streams
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:
      type: integer(4)
      primary: true
      unsigned: true
      notnull: true
      autoincrement: true
    video_id:
      type: integer(4)
      unsigned: true
      notnull: true
    type:
      type: string(1000)
      notnull: true
    status:
      type: enum
      values: ['not_processed','processing','error','processed']
      notnull: true
      default: not_processed
    is_source:
      type: integer(1)
      unsigned: true
      notnull: true
      default: 1
  relations:
    Video:
      class: Companies_Model_CompanyVideo
      local: video_id
      foreign: id
      foreignAlias: Streams
      onDelete: cascade
      onUpdate: cascade
