<h1 class="page-title"><?php echo $this->escape(isset($this->customTitle) ? $this->customTitle : $this->title); ?></h1>
<hr>

<form enctype="application/x-www-form-urlencoded" method="post" class="form-horizontal" action="<?php echo $this->form->getAction(); ?>">
    <fieldset>
        <?php echo $this->form->csrf_token; ?>

        <?php
            foreach ($this->form->getElements() as $element):
                if ($element->getName() == 'csrf_token') {
                    continue;
                }
        ?>
            <div class="control-group <?php if ($element->getMessages()) echo 'error'; ?>">
                <label class="control-label" for="<?php echo $element->getId(); ?>"><?php echo $element->getLabel(); $element->setLabel(''); ?></label>
                <div class="controls">
                    <?php echo $element; ?>

                    <?php if ($element->getMessages()): ?>
                        <span class="help-block"><?php echo implode('', $element->getMessages()); ?></span>
                    <?php elseif ($element->getDescription()): ?>
                        <span class="help-block"><?php echo $element->getDescription(); ?></span>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Create</button>
            </div>
        </div>
    </fieldset>
</form>