<br>
<style>
    .revudio-company-block-square {
        border:1px solid #818181;
        width:300px;
        border-radius:10px;
        -webkit-border-radius:10px;
        -moz-border-radius:10px;
        margin-top:10px;
        padding:0;
        font-family:Tahoma, Verdana;
        cursor:pointer;
        background-color:white;
    }

    .revudio-company-block-square-title{
        display: block;
        text-align: center;
        font-weight: bold;
        border-bottom: 1px solid #818181;
        margin: 0 -10px 10px;
        padding-bottom: 10px;
    }

    .revudio-company-block-top-square {
        padding:10px;
        border-bottom:1px solid #818181;
        overflow:hidden;
        margin:0;
    }

    .revudio-company-block-top-left-square {
        float:left;
        width:48px;
        margin:0;
        padding:0;
        height:37px;
    }

    .revudio-company-block-top-right-square {
        float:left;
        width:150px;
        height:37px;
        margin-left:20px;
    }

    .revudio-company-block-top-reviews-square {
        height:20px;
        padding:0;
        margin-bottom:1px;
        font-size:13px;
        font-family:Arial;
        font-weight:bold;
        color:#3c3c3c;
    }

    .revudio-company-block-top-rating-square {
        height:17px;
        padding:0;
        font-size:12px;
        font-weight:bold;
        overflow:hidden;
    }

    .revudio-star-rating-square {
        float:left;
        margin-right:10px;
    }

    .revudio-star-rating-square img {
        float:left;
    }

    .revudio-letter-rating-square {
        float:left;
        color:#4c9bfa;
        line-height:95%;
    }

    .revudio-company-block-reviews-square {
        padding:10px;
        margin:0;
    }

    .revudio-company-block-reviews-inner-square {
        padding:10px;
        margin:0;
        border:1px solid #818181;
        border-radius:5px;
        -webkit-border-radius:5px;
        -moz-border-radius:5px;
        list-style:none;
        font-size:80%;
        background:url("<?php echo $this->serverUrl(); ?>/images/banner/background-square.png") top right no-repeat;
    }

    .revudio-company-block-reviews-inner-square li {
        border-bottom:1px dashed #ddd;
        padding:5px 0 5px 0;
        font-size:14px;
    }

    .revudio-company-block-reviews-inner-square li:first-child {
        padding-top:0;
    }

    .revudio-company-block-reviews-inner-square li:last-child {
        border-bottom:none;
        padding-bottom:0;
    }

    .revudio-company-block-reviews-review-top-square {
        overflow:hidden;
        height:20px;
    }

    .revudio-review-star-rating-square {
        float:left;
        margin-right:0;
        padding:0;
    }

    .revudio-review-client-name-square {
        float:left;
        font-weight:bold;
        color:#000;
        margin-left:10px;
    }

    .revudio-review-text-square {
        color:#3e3e3e;
        font-size:14px;
    }

    .revudio-signature-square {
        color:#fff;
        background-color:#4c9bfa;
        padding:2px;
        margin:0px 10px 10px 10px;
        border-radius:5px;
        -webkit-border-radius:5px;
        -moz-border-radius:5px;
        font-weight:normal;
        text-align: center;
        font-size:15px;
    }
</style>

<div class="revudio-company-block-square">
    <div class="revudio-company-block-top-square">
        <div class="revudio-company-block-square-title">
            <?php echo $this->company->name; ?>
        </div>
        <div class="revudio-company-block-top-left-square">
            <img alt="Reviews For <?php echo $this->company->name ?>" title="Reviews For <?php echo $this->company->name ?>" src="<?php echo $this->serverUrl(); ?>/images/banner/icon.png">
        </div>
        <div class="revudio-company-block-top-right-square">
            <div class="revudio-company-block-top-reviews-square">
                <?php echo $this->company->review_count; ?> Customer Reviews
            </div>
            <div class="revudio-company-block-top-rating-square">
                <div class="revudio-star-rating-square" id="revudio-company-rating">
                    <?php for ($i = 0; $i < 5; $i++): ?>
                        <?php
                            $star = "off";

                            if ($this->ratings["star"]->getRating() >= $i + 1) {
                                $star = "on";
                            }
                        ?>

                        <img src="<?php echo $this->serverUrl(); ?>/images/banner/stars/star-<?php echo $star; ?>.png" alt="<?php echo $i + 1; ?>" title="<?php echo $i + 1; ?>">
                    <?php endfor; ?>
                </div>

                <div class="revudio-letter-rating-square">
                    <?php echo $this->ratings['percent']->getRating(); ?>%
                    <?php echo $this->ratings['letter']->getRating() ?>
                </div>
            </div>
        </div>
    </div>
    <div class="revudio-company-block-reviews-square">
        <?php if (count($this->reviews) > 0): ?>
            <ul class="revudio-company-block-reviews-inner-square">
                <?php foreach ($this->reviews as $review):?>
                    <li>
                        <div class="revudio-company-block-reviews-review-top-square">
                            <?php $ratings = $this->ratings()->getAllRatings($review->rating); ?>

                            <div class="revudio-review-star-rating-square" id="revudio-review-rating-<?php echo $review->id; ?>">
                                <?php for ($i = 0; $i < 5; $i++): ?>
                                    <?php
                                        $star = "off";
                                        $rating = $ratings["star"]->getRating();

                                        if ($rating >= $i + 1) {
                                            $star = "on";
                                        }

                                        if ($rating > $i && $rating < $i + 1) {
                                            $star = "half";
                                        }
                                    ?>

                                    <img src="<?php echo $this->serverUrl(); ?>/images/banner/stars/star-<?php echo $star; ?>.png" alt="<?php echo $i + 1; ?>" title="<?php echo $i + 1; ?>">
                                <?php endfor; ?>
                            </div>

                            <div class="revudio-review-client-name-square"><?php echo $this->escape($review->client_name); ?></div>
                        </div>

                        <?php
                            if ($review->review):
                                $text = $review->review;

                                if (mb_strlen($text) > 80) {
                                    $text = mb_substr($text, 0, 80, 'UTF-8') . "...";
                                }

                                $text = htmlspecialchars($text, ENT_QUOTES);
                        ?>
                            <div class="revudio-review-text-square">
                                <?php echo $text; ?>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            No reviews yet.
        <?php endif; ?>
    </div>
    <div class="revudio-signature-square">
        Revudio Trusted Review Source
    </div>
</div>