<div class="about-us">
    <div class="row-fluid">
        <div class="span7">
            <div class="about-title">
                <h2>Learn More About Us</h2>
            </div>
            <div class="about-content">
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop.</p>
            </div>
        </div>
        <div class="span5">
            <div class="about-image">
                <img src="/images/about-us.jpg" />
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="about-print">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type.
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <div class="about-mid-left">
                <h2 class="a-heading">What makes us different than the other marketing companies?</h2>
                <ul class="about-p">
                    <li>We don’t require long terms contracts!</li>
                    <li>All our sites are custom, search engine friendly website designs!</li>
                    <li>We limit the law firms we work with to 3 per geographic area to help ensure that all our clients are successfully generating new business on a consistent basis!</li>
                    <li>Accountability! We offer call tracking phone numbers and website analytics to monitor the performance of your website.</li>
                </ul>
            </div>
        </div>
        <div class="span6">
            <div class="about-mid-right">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </div>
        </div>
    </div>
</div>
<div class="faq">
    <div class="row-fluid">
        <div class="span12">

        </div>
    </div>
</div>