<style>
    input[type=text]{
        width:280px
    }

    textarea{
        width:280px;
        height:150px;
    }

    dt{float:left;}

    dd {
        margin-left: 130px;
    }

    table tr:last-child {
       display: none;
    }
</style>

<div class="special-static">
    <div class="content_area_inner_top">
        <img style="width: 100%;" src="/images/banner/revudio-banner-revised.png" />
    <!--<div class="content_area_inner_left_price">
        <h1>Business Class Bundle</h1>
        <img src="/images/arrow.png" width="36" height="48">

        <div class="para2">
            <ul>
                <li>Tablet secure case with keypad cable locking system</li>
                <li>Tablet stand for display</li>
                <li>10ft USB power extender for IPAD</li>
                <li>Display Instructions</li>
                <li>Businesss Profile Setup</li>
                <li>Revudio App</li>
                <li>Free Up Search Analysis</li>
            </ul>
        </div>
    </div>

    <div class="content_area_inner_left_price2">
    <h1>BUSINESS CLASS</h1>
    <div class="para3">
    <ul>
    <li> $159.00</li>
    <li style="color: #ff6600;font-size: 19px;margin:0px;"> Bundle Cost</li>
    <li> $49.00</li>
    <li style="color: #ff6600;font-size: 19px;margin:0px;"> Monthly</li>
    <li><a href="<?php echo $this->url("signup"); ?>?plan=4"><img src="images/button.png"></a></li>
    </ul>
    </div>
    </div>
    <div class="content_area_inner_left_price2">
    <h1>SERVICE CLASS</h1>
    <div class="para3">
    <ul>
    <li> $99.00</li>
    <li style="color: #ff6600;font-size: 19px;margin:0px;"> Set Up Fee</li>
    <li> $49.00</li>
    <li style="color: #ff6600;font-size: 19px;margin:0px;"> Monthly</li>
    <li><a href="<?php echo $this->url("signup"); ?>?plan=3"><img src="images/button.png"></a></li>
    </ul>
    </div>
    </div>-->

        <!--content_area_inner_right-->


    <div class="content_area_inner_mid">
    <div class="beni"><img src="/images/benifites.png" width="557" height="28"></div>
    <div class="points">
    <ul><li>System to remarket to loyal customers through email
    for future promotions and discounts.</li><li>Reconnect with customers for return business
    potential.</li><li>Gives credibility to business owners from legitimate
    ratings by real customers.</li><li>Personal business profile through Revudio with unique
    business information &amp; user features.</li><li>Real time review banner or icon script on business
    owners website.</li><li>Unique way to engage customers personally through
    our system.</li></ul>
    <a href="#">And Much More...</a>
    </div><!--points-->
    <div class="contact_form">
    <h5>CONTACT US</h5>
    <p>To learn more about our services feel free to email us below.</p>
    <div class="big-divider">
    </div><!--divider-->

    <form action="/pricing" method="post" name="contactus" id="contactus">
        <?php echo $this->form->getElement("csrf_token"); ?>
        <input type="text" value="Name:" name="name" id="txtname">
        <input type="text" value="Phone:" name="phone" id="txtphone" >
        <input type="text" value="Email:"name="email" id="txtemail" >
        <input type="text" value="How did you hear about us?" name="hear" id="txthear" >
        <textarea value="" name="comment" id="txtcomment" >Comment:</textarea>

        <div class="big-divider">
        </div><!--divider-->
        <input type="button" id="button">
    </form>
    <?php if($this->sentemail){
    echo "<div style='clear:both; color: #FF6600;    padding: 10px;    text-align: center;'>Email Sent Successfully</div>";
    }?>
    </div><!--contact_form-->
    </div><!--content_area_inner_mid-->
    <div class="content_area_inner_bottom">
    <h6>Have questions? We got answers:</h6>
    <div class="pagecontent">
    <div class="heading">
    How does the free 30-day trial work?
    </div><!--heading-->
    <p>&nbsp;</p>
    </div><!--content-->
    <div class="pagecontent content_right">
    <div class="heading">
    Can I get help setting up my profile?
    </div><!--heading-->
    <p>&nbsp;</p>
    </div><!--content-->
    <div class="pagecontent">
    <div class="heading">
    What if I have more than one business?
    </div><!--heading-->
    <p>&nbsp;</p>
    </div><!--content-->
    <div class="pagecontent content_right">
    <div class="heading">
    Can I cancel anytime?
    </div><!--heading-->
    <p>&nbsp;</p>
    </div><!--content-->
    </div><!--content_area_inner_bottom-->
    </div>
</div>
