<p>
    <b>Information We Collect and Policies</b>
</p>

<p>
    Network Local, LLC (“Network Local”, “we”, “us” or “our”) respects your privacy. This privacy policy (the “Privacy Policy”) explains what information we may collect about you, how we and other companies may use it, and tracking technologies that may be used to collect information.
</p>

<p>
    We only collect information that is provided by the business. When they sign up for our monthly services and all information related to them is strictly and solely provided by the owner or persons handling the business profile account.
</p>

<p>
    By using the Services you consent to our gathering, use and disclosure of your information, as described in this Privacy Statement, the Terms of Service and the other documents, agreements and materials incorporated therein (collectively referred to as the “Rules”). This Privacy Policy may change from time to time RevUdio will provide notice of changes under our privacy policy page.
</p>

<ol>
    <li><b>Cookies:</b> Cookies are small data files that may have unique identifiers, and reside, among other places, on your computer or mobile device, in emails we send to you, and on our web pages. Cookies may transmit information about you and your use of the Site, such as your browser type, search preferences, data relating to advertisements that have been displayed to you or that you have clicked on, and the date and time of your use. You can disable some (but not all) Cookies in your device or browser settings, but doing so may affect your ability to use the Site. To learn how to manage privacy and storage settings for local shared objects in particular, click <a href="http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager.html#117118">here</a>.</li>
    <li><b>Apps:</b> Our Apps are created for the sole purpose to give the client the ability to obtain reviews and reviews only.</li>
    <li><b>Sharing:</b> We do not share any of our information to third party software companies or other media share providers. Our information is strictly kept in a secured database and is used for client customer privileges. Third Party Sites and Co-Branded Services. RevUdio will not sell Services to advertising firms, promote, reference, recommend or provide links to third party sites, services and products.</li>
    <li><b>Refund Policy:</b> Once the Client has signed up and paid he has acknowledged and is bound by a month to month contract and can cancel at any time. The cancelation is provided in there admin area in profile. There is a no refund policy as this a paid subscription once cancelled then the profile will be removed and is effective immediately upon cancellation.</li>
    <li><b>Links:</b> The Site may contain links to unaffiliated third party websites. Except as set forth herein, we do not share your personal information with them, and are not responsible for their privacy practices. We suggest you read the privacy policies on all such third party websites</li>
    <li><b>Personal Information:</b> All information is obtained and created by the business owner or manager of the profile. This data will be displayed publicly and is the sole responsibility of the business owner to be accurate and aware that this information is to be correct and true to the actual business and location.</li>
    <li>
        <b>Payment Details & Cancellation</b>
        <p>
            For month-to-month paid services, you will be billed on the subscription anniversary day each subsequent month. On the last day of the subscription anniversary each month, the service will automatically be renewed for the next month unless you cancel the service as described in the Cancellation of Service section of this Billing Policy.
        </p>
        <p>
            For monthly paid services, the service term begins the day the service is purchased and continues until the end of the applicable subscription period. On the last day of each applicable term, your service will automatically renew for successive terms of the same duration.Credit card payments that cannot be processed on the applicable anniversary bill date may cause your account to be suspended. Once your account is suspended, you will need to contact Customer Support to reactivate it.
        </p>
    </li>
    <li><b>Email Information:</b> We may use an e-mail delivery system to send you e-mails regarding our services and or upcoming new features. Pixel tags and cookies are used in those e-mail messages and at our website to help us measure the effectiveness of our advertising and how visitors use our site.</li>
</ol>

<p>
    <br>
    <b>Disputes</b><br>
    If you have any questions about RevUdio and our guidelines please feel free to contact us at:
    <br><br>

    <em>
        <b>RevUdio</b><br>
        13215 Se Mill Plain Blvd C8-234<br>
        Vancouver Wa 98682<br>
        Contact us
    </em>
</p>
